NicklasSoderberg/Whistleblower

- Whistleblower/Content/bootstrap.css
- Whistleblower/Controllers/HomeController.cs
- Whistleblower/Views/Home/Safebox.cshtml
- Whistleblower/Whistleblower.csproj
lade till i bootstrap.css för popuprutan. och skapade en ny view Safebox.cshtml
> Skapa Safebox Viewn och gjorde klart en basic popup för att svara.

- Whistleblower/Content/bootstrap.css
- Whistleblower/Controllers/HomeController.cs
- Whistleblower/Models/WhistleModel.cs
- Whistleblower/Views/Home/Whistle.cshtml
Uppfyller nu kraven för sidan whistle.
> Uppfyller nu kraven för sidan whistle.

- Whistleblower/Controllers/HomeController.cs
- Whistleblower/Models/LoginModel.cs
- Whistleblower/Views/Home/UserLogin.cshtml
Added caps-lock message, show and hide password checkbox, redirect to another view when logged in, only number input on password box and if trying to log in with wrong password or id error msg shows up telling user.
> User login page

- Whistleblower/Content/bootstrap.css
- Whistleblower/Controllers/HomeController.cs
- Whistleblower/Views/Home/Whistle.cshtml
- Whistleblower/Views/Home/WhistleConfirm.cshtml
Skapa ärende är nu presenterbart
> Skapa ärende är nu presenterbart

- Whistleblower/Models/LoginModel.cs
- Whistleblower/Views/Home/UserLogin.cshtml
> changed label to required for and centered whole page

- Whistleblower/Controllers/LoginController.cs
- Whistleblower/Custom/DBHandler.cs
- Whistleblower/Models/LoginModel.cs
- Whistleblower/Views/Login/UserLogin.cshtml
Login is working fully now with temporary given id and password
> Check login credentials in database to login if not working get error

- Whistleblower/Controllers/LawyerController.cs
- Whistleblower/Controllers/SafeboxController.cs
- Whistleblower/Custom/DBHandler.cs
- Whistleblower/ViewModels/LawyerViewmodel.cs
> Fixed the Lawyer login

- Whistleblower/Custom/DBHandler.cs
- Whistleblower/Views/Admin/EditWhistle.cshtml
> You can now change Lawyers

- Whistleblower/Controllers/AdminController.cs
- Whistleblower/Custom/DBHandler.cs
- Whistleblower/Views/Admin/Dashboard.cshtml
- Whistleblower/Views/Admin/EditWhistle.cshtml
> Small edit

- Whistleblower/Controllers/AdminController.cs
- Whistleblower/Views/Admin/Dashboard.cshtml
Added filter to admin dashboard
> Added filter to admin dashboard

- Whistleblower/Views/Admin/Dashboard.cshtml
- Whistleblower/Views/Whistle/WhistleConfirm.cshtml
> Added more functions

- Whistleblower/Controllers/AdminController.cs
- Whistleblower/Controllers/LawyerController.cs
- Whistleblower/ViewModels/LawyerViewmodel.cs
- Whistleblower/Views/Lawyer/WhistleHandler.cshtml
Redid filter & added search for lawyer
> Redid filter & added search for lawyer

- Whistleblower/Encryption/Helper.cs
> Update for Helper.cs

- Whistleblower/Custom/DBHandler.cs
- Whistleblower/ViewModels/LawyerViewmodel.cs
- Whistleblower/Views/Lawyer/Whistle.cshtml
> Added preview of pictures

- Whistleblower/Views/Lawyer/WhistleHandler.cshtml
> Fixed labels

- Whistleblower/ViewModels/SafeboxViewmodel.cs
- Whistleblower/Views/Safebox/Safebox.cshtml
> Added file preview in safebox

- Whistleblower/Controllers/AdminController.cs
- Whistleblower/Controllers/LoginController.cs
- Whistleblower/Views/Admin/Dashboard.cshtml
implemterade login för admin men utan kryptering tills vi har en lösning för det
> implementerade login för admin

- Whistleblower/Controllers/LawyerController.cs
- Whistleblower/Controllers/SafeboxController.cs
- Whistleblower/Custom/DBHandler.cs
- Whistleblower/Models/Mail.cs
- Whistleblower/Views/Lawyer/Whistle.cshtml
- Whistleblower/Views/Safebox/Safebox.cshtml
- Whistleblower/Views/Whistle/WhistleConfirm.cshtml
- Whistleblower/Whistleblower.csproj
- Whistleblower/packages.config
File support done, also in messages.  + downloads, and .zip file
> File support done, also in messages. + downloads, and .zip file

- Whistleblower/Controllers/LawyerController.cs
- Whistleblower/Custom/DBHandler.cs
- Whistleblower/Views/Lawyer/Whistle.cshtml
- Whistleblower/Views/Safebox/Safebox.cshtml
- Whistleblower/Web.config
> Ready for demo 4

- Whistleblower/Models/LawyerModel.cs
- Whistleblower/Views/Admin/Dashboard.cshtml
- Whistleblower/Views/Lawyer/Login.cshtml
- Whistleblower/Views/Lawyer/Whistle.cshtml
- Whistleblower/Views/Lawyer/WhistleHandler.cshtml
- Whistleblower/Views/Login/LoginAdmin.cshtml
- Whistleblower/Views/Login/ReportStatus.cshtml
- Whistleblower/Views/Login/UserLogin.cshtml
- Whistleblower/Views/Safebox/Safebox.cshtml
- Whistleblower/Views/Shared/_Layout.cshtml
- Whistleblower/Views/Whistle/Index.cshtml
- Whistleblower/Views/Whistle/Whistle.cshtml
- Whistleblower/Views/Whistle/WhistleConfirm.cshtml
> Design updates

- Whistleblower/Views/Lawyer/WhistleHandler.cshtml
- Whistleblower/Views/Safebox/Safebox.cshtml
> Send message now fixed

- Whistleblower/Views/Lawyer/WhistleHandler.cshtml
- Whistleblower/Views/Safebox/Safebox.cshtml
> More design updates
